### ISSUE TITLE
Refusing to enable OSPRay since either the client or server does not have it.

### ISSUE THREAD

**Issue by josephwinston** [NVIDIA/ipyparaview#3]
When running `ipyparaview/notebooks/Iso-Surfaces_with_RTX.ipynb`, I receive the following error:

```
(   5.905s) [paraview        ]    vtkPVRenderView.cxx:3119  WARN| vtkPVRenderView (00000295001E2DE0): Refusing to enable OSPRay since either the client or server does not have it.
```

This comes about of course since I installed paraview like this:
``` 
conda create --name paraview python=3.8
conda activate paraview
conda install notebook
```

I approached the install this way to prevent having to download paraview and then set up python paths appropriately.  Is this way of wanting to use conda madness?

**Comment by NickLeaf** [comment]
The warning message you posted shows up when ParaView can't enable the ray tracing back end. It shouldn't prevent you from rendering with the normal OpenGL mode (the first three cells in that notebook). I _think_ the warning is safe to ignore if you only want to use the OpenGL back-end.

At a glance, since you're getting a ParaView-specific warning message, then it looks like your installation method works fine. I've been using a non-conda install of ParaView, myself, so I can mess around some features that aren't available in the ParaView package that's up on conda-forge.
